ServerEvents.recipes(event => {
    event.recipes.gtceu.assembler("")
        .itemInputs("4x gtceu:polyethylene_plate")
        .itemInputs("8x gtceu:steel_plate")
        .itemInputs("7x tacz:ammo")
        .itemInputs("gtceu:lv_electric_motor")
        .itemInputs("gtceu:lv_electric_piston")
        .itemInputs("2x gtceu:steel_ring")
        .itemInputs("gtceu:steel_rod")
        .itemInputs("4x gtceu:steel_screw")
        .itemOutputs("tacz:modern_kinetic_gun")
        .EUt(32)
        .duration(50)
})