ServerEvents.recipes(event => {
    event.recipes.gtceu.assembler("")
        .itemInputs("4x gtceu:polyethylene_plate")
        .itemInputs("8x gtceu:steel_plate")
        .itemInputs(Item.of('7x tacz:ammo', '{AmmoId:"tacz:9mm"}'))
        .itemInputs("2x gtceu:steel_ring")
        .itemInputs("gtceu:steel_rod")
        .itemInputs("4x gtceu:steel_screw")
        .itemOutputs(Item.of('tacz:modern_kinetic_gun', '{GunCurrentAmmoCount:17,GunFireMode:"SEMI",GunId:"tacz:glock_17",HasBulletInBarrel:1b}'))
        .EUt(32)
        .duration(50)
})